FROM databricksruntime/minimal:latest

RUN  apt-get update \
    && apt-get install -y libnetcdf-dev \
    && apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev libv8-dev \
    && apt-get install -y libproj-dev \
    && apt-get install -y libudunits2-0 libudunits2-dev \
    && apt-get install -y gdal-bin proj-bin libgdal-dev libproj-dev \
    && apt-get install -y libx11-dev \
    && apt install -y libnetcdf-* 

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

RUN apt install -y apt-transport-https software-properties-common \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 \
    && add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'

RUN apt update \
    && apt-get install --yes \
    libssl-dev \
    r-base \
    r-base-dev

RUN add-apt-repository -r 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial-cran35/' \
    && apt-key del E298A3A825C0D65DFD57CBB651716619E084DAB9 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN R -e "install.packages('remotes');" --silent --no-echo \
    && R -e "remotes::install_version('ncdf4', '1.17')" --silent --no-echo \
    && R -e "remotes::install_version('reshape', '0.8.8')" --silent --no-echo \
    && R -e "remotes::install_version('reshape2', '1.4.4')" --silent --no-echo \
    && R -e "remotes::install_version('flock', '0.7')" --silent --no-echo \
    && R -e "remotes::install_version('rasterVis', '0.49')" --silent --no-echo \
    && R -e "remotes::install_version('furrr', '0.2.1')" --silent --no-echo \
    && R -e "remotes::install_version('here', '1.0.0')" \
    && R -e "remotes::install_version('dplyr', '1.0.2')" \
    && R -e "remotes::install_version('tidyverse', '1.3.0')" \
    && R -e "remotes::install_version('sf', '0.9-6')" \
    && R -e "remotes::install_version('knitr', '1.30')" \
    && R -e "remotes::install_version('Matrix', '1.2-18')" \
    && R -e "remotes::install_version('rgl', '0.100.054')"  \
    && R -e "remotes::install_version('rgdal', '1.5-18')"  \
    && R -e "remotes::install_version('plot3D', '1.3')"  \
    && R -e "remotes::install_version('future', '1.21.0')" \
    && R -e "remotes::install_version('gridExtra', '2.3')" 


RUN R -e "install.packages(c('hwriterPlus'), repos='https://mran.revolutionanalytics.com/snapshot/2017-02-26')" \
 && R -e "install.packages(c('htmltools'), repos='https://cran.microsoft.com/')" \
 && R -e "install.packages('Rserve', repos='http://rforge.net/')"


COPY Rprofile.site /usr/lib/R/etc/Rprofile.site

# Rstudio installation.
RUN apt-get update \
 # Installation of rstudio in databricks needs /usr/bin/python.
 && apt-get install -y python \
 # Install gdebi-core.
 && apt-get install -y gdebi-core \
 # Download rstudio 1.2 package for ubuntu 16.04 and install it.
 && apt-get install -y wget \
 && wget https://download2.rstudio.org/server/trusty/amd64/rstudio-server-1.2.5042-amd64.deb -O rstudio-server.deb \
 && gdebi -n rstudio-server.deb \
 && rm rstudio-server.deb